name = "polynomial_sequences"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["PolynomialSequences"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
# autoImplicit = false
# relaxedAutoImplicit = false
# weak.linter.mathlibStandardSet = true
# maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4"
rev = "v4.22.0"

[[lean_lib]]
name = "PolynomialSequences"
